name: movie-monad
version: '0.0.6.0'
summary: A free and simple to use video player made with Haskell.
type: app
description: |
  Movie Monad is a free and simple to use video player.
  You can play files on your computer or stream videos from the web.
  Movie Monad gets out of the way so you can watch the videos you love.
  Try it out.
icon: snap/gui/movie-monad-icon.svg
grade: stable
confinement: strict

apps:
  movie-monad:
    command: desktop-launch $SNAP/usr/bin/movie-monad
    desktop: ../snap/gui/movie-monad.desktop
    plugs:
      - network
      - opengl
      - desktop
      - desktop-legacy
      - unity7
      - wayland
      - x11
      - alsa
      - pulseaudio
      - gsettings
      - screen-inhibit-control
      - optical-drive
      - removable-media
      - raw-usb
      - mount-observe
      - home

parts:
  movie-monad:
    source: .
    source-tag: nil
    plugin: nil
    build-packages:
      - libtinfo-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-good1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer-plugins-bad1.0-dev
      - libgirepository1.0-dev
    stage-packages:
      - libgirepository-1.0-1
      - libgstreamer1.0-0
      - libgstreamer-plugins-base1.0-0
      - libgstreamer-plugins-good1.0-0
      - libgstreamer-plugins-bad1.0-0
      - gstreamer1.0-libav
      - gstreamer1.0-plugins-base-apps
      - gstreamer1.0-pulseaudio
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
    build-attributes:
      - no-system-libraries
    prepare: |
    build: |
    install: |
      export LD_LIBRARY_PATH=''
      export _MOVIE_MONAD_DOWNLOAD_DIR=$SNAPCRAFT_PROJECT_NAME-linux-$SNAPCRAFT_PROJECT_VERSION
      export _MOVIE_MONAD_DOWNLOAD_FILE=$_MOVIE_MONAD_DOWNLOAD_DIR.tar.gz
      wget https://github.com/lettier/$SNAPCRAFT_PROJECT_NAME/releases/download/$SNAPCRAFT_PROJECT_VERSION/$_MOVIE_MONAD_DOWNLOAD_FILE
      tar -zxvf $_MOVIE_MONAD_DOWNLOAD_FILE
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/
      cd $_MOVIE_MONAD_DOWNLOAD_DIR/
      cp -RP . $SNAPCRAFT_PART_INSTALL/usr/
    prime:
      - -home/*
    after:
      - desktop-gtk3
