name: movie-monad
version: '0.0.4.0'
summary: A free and simple to use video player built with Haskell.
type: app
description: |
  Movie Monad is a free and simple to use video player.
  You can play local files or files from the web.
  Movie Monad gets out of the way so you can watch the videos you love.
  Try it today.
icon: snap/gui/movie-monad.svg
grade: stable
confinement: strict

apps:
  movie-monad:
    command: desktop-launch $SNAP/usr/bin/movie-monad
    desktop: ../snap/gui/movie-monad.desktop
    plugs:
      - network
      - opengl
      - desktop
      - desktop-legacy
      - unity7
      - wayland
      - x11
      - alsa
      - pulseaudio
      - gsettings
      - screen-inhibit-control
      - optical-drive
      - removable-media
      - raw-usb
      - mount-observe
      - home

parts:
  movie-monad:
    source: https://github.com/lettier/movie-monad.git
    source-tag: 0.0.4.0
    plugin: nil
    build-packages:
      - build-essential
    stage-packages:
      - libcanberra-gtk-module
      - libgstreamer1.0-0
      - libgstreamer-plugins-base1.0-0
      - libgstreamer-plugins-good1.0-0
      - libgstreamer-plugins-bad1.0-0
      - gstreamer1.0-libav
      - gstreamer1.0-plugins-base-apps
      - gstreamer1.0-pulseaudio
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
    prepare: |
      if [ ! `command -v stack` ]; then
        curl -sSL https://get.haskellstack.org/ | sh -s - -f
      fi
      make setup
      make cabal_update
    build: |
      make cabal_install_relocatable_executable
    install: |
      export _GHC_VERSION="8.0.2"
      export _GHC_DIR="x86_64-linux-ghc-"$_GHC_VERSION
      export _MOVIE_MONAD_VERSION_DIR=$SNAPCRAFT_PROJECT_NAME-$SNAPCRAFT_PROJECT_VERSION
      export LD_LIBRARY_PATH=$SNAP/usr/lib/$_GHC_DIR
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/bin \
               $SNAPCRAFT_PART_INSTALL/usr/lib/$_GHC_DIR \
               $SNAPCRAFT_PART_INSTALL/usr/share/$_GHC_DIR/$_MOVIE_MONAD_VERSION_DIR \
               $SNAPCRAFT_PART_INSTALL/usr/share/doc/$SNAPCRAFT_PROJECT_NAME
      cp .cabal-sandbox/bin/$SNAPCRAFT_PROJECT_NAME $SNAPCRAFT_PART_INSTALL/usr/bin/
      find .cabal-sandbox/lib/$_GHC_DIR/ -type f -name '*.so' \
        | xargs cp -t $SNAPCRAFT_PART_INSTALL/usr/lib/$_GHC_DIR/
      cp -R .cabal-sandbox/share/$_GHC_DIR/$_MOVIE_MONAD_VERSION_DIR/. \
            $SNAPCRAFT_PART_INSTALL/usr/share/$_GHC_DIR/$_MOVIE_MONAD_VERSION_DIR/
      cp -R .cabal-sandbox/share/doc/$_GHC_VERSION_DIR/* \
            $SNAPCRAFT_PART_INSTALL/usr/share/doc/$SNAPCRAFT_PROJECT_NAME/
    after:
      - desktop-gtk3
