name: movie-monad
version: '0.0.4.0'
summary: A free and simple to use video player built with Haskell.
type: app
description: |
  Movie Monad is a free and simple to use video player.
  You can play local files or files from the web.
  Movie Monad gets out of the way so you can watch the videos you love.
  Try it today.
icon: snap/gui/movie-monad.svg
grade: stable
confinement: strict

apps:
  movie-monad:
    command: desktop-launch $SNAP/bin/movie-monad
    desktop: ../snap/gui/movie-monad.desktop
    plugs:
      - network
      - opengl
      - desktop
      - desktop-legacy
      - unity7
      - wayland
      - x11
      - alsa
      - pulseaudio
      - gsettings
      - screen-inhibit-control
      - optical-drive
      - removable-media
      - raw-usb
      - home

parts:
  movie-monad:
    source: https://github.com/lettier/movie-monad.git
    source-tag: 0.0.4.0
    plugin: nil
    build-packages:
      - build-essential
    stage-packages:
      - dbus-x11
      - x11-xserver-utils
      - libcanberra-gtk-module
      - libgstreamer1.0-0
      - libgstreamer-plugins-base1.0-0
      - libgstreamer-plugins-good1.0-0
      - libgstreamer-plugins-bad1.0-0
      - gstreamer1.0-libav
      - gstreamer1.0-plugins-base-apps
      - gstreamer1.0-pulseaudio
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
    prepare: |
      curl -sSL https://get.haskellstack.org/ | sh -s - -f
      make setup
      make update
      make cabal_update
    build: |
      make cabal_install_relocatable_executable
    install: |
      cp -R .cabal-sandbox/bin ../install/
      cp -R .cabal-sandbox/lib ../install/
      cp -R .cabal-sandbox/share ../install/
    after:
      - desktop-gtk3
